# Generated by Django 4.2.3 on 2023-07-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageDoc', '0003_alter_document_file_documentversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_conversion', to=settings.AUTH_USER_MODEL),
        ),
    ]
